AllCops:
  Includes:
    - Rakefile
    - Gemfile
    - /*.rb
    - /**/*.rb
Documentation:
    Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 120