AllCops:
  Includes:
    - Gemfile
    - /*.rb
    - /**/*.rb
  TargetRubyVersion: 2.3
Documentation:
    Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/ParameterLists:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false